server.port: 9003

spring:
  aop:
    proxy-target-class: true
  redis:
    password: mypassword
    sentinel:
      master: mymaster
      nodes: 211.49.172.81:27000,211.49.172.81:27001,211.49.172.81:27002
